"""initial schema

Revision ID: ba09a90b3bf6
Revises: 
Create Date: 2026-06-27 03:35:10.180171
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db  # noqa: F401  (provides the portable GUID type used below)


revision: str = 'ba09a90b3bf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('training_dataset', sa.String(), nullable=True),
    sa.Column('threshold_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('patients',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('external_code', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('anonymized_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_external_code'), ['external_code'], unique=False)

    op.create_table('users',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('user_id', app.core.db.GUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('studies',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('patient_id', app.core.db.GUID(), nullable=True),
    sa.Column('patient_code', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('view', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('image_format', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studies_status'), ['status'], unique=False)

    op.create_table('predictions',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('study_id', app.core.db.GUID(), nullable=False),
    sa.Column('model_version_id', app.core.db.GUID(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('inference_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_study_id'), ['study_id'], unique=False)

    op.create_table('prediction_findings',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('prediction_id', app.core.db.GUID(), nullable=False),
    sa.Column('finding_code', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=True),
    sa.Column('heatmap_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_findings_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('study_id', app.core.db.GUID(), nullable=False),
    sa.Column('prediction_id', app.core.db.GUID(), nullable=True),
    sa.Column('reviewer_id', app.core.db.GUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('final_report', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_study_id'), ['study_id'], unique=False)

    op.create_table('review_findings',
    sa.Column('id', app.core.db.GUID(), nullable=False),
    sa.Column('review_id', app.core.db.GUID(), nullable=False),
    sa.Column('finding_code', sa.String(), nullable=False),
    sa.Column('final_label', sa.Boolean(), nullable=False),
    sa.Column('diverged_from_ai', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_findings_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_findings_review_id'))

    op.drop_table('review_findings')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_study_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('prediction_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_findings_prediction_id'))

    op.drop_table('prediction_findings')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_study_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studies_status'))

    op.drop_table('studies')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_external_code'))

    op.drop_table('patients')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
